firebase deploy
=== Deploying to 'autobook-s0cch'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect, apphosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@1.0.0 lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
    2:1  error    This line has a length of 96. Maximum allowed is 80  max-len
  104:7  warning  '_context' is defined but never used                 @typescript-eslint/no-unused-vars

✖ 2 problems (1 error, 1 warning)

Error: functions predeploy error: Command terminated with non-zero exit code 1