i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect, apphosting Running command: npm --prefix "$RESOURCE_DIR" run lint
> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
   11:1   error    Missing JSDoc return type                             valid-jsdoc
   13:4   error    Use @return instead                                   valid-jsdoc
   21:1   error    This line has a length of 88. Maximum allowed is 80   max-len
   23:1   error    This line has a length of 89. Maximum allowed is 80   max-len
   26:1   error    This line has a length of 88. Maximum allowed is 80   max-len
   32:1   error    This line has a length of 89. Maximum allowed is 80   max-len
   39:1   error    This line has a length of 89. Maximum allowed is 80   max-len
   40:1   error    This line has a length of 94. Maximum allowed is 80   max-len
   41:1   error    This line has a length of 91. Maximum allowed is 80   max-len
   45:1   error    This line has a length of 146. Maximum allowed is 80  max-len
   46:1   error    This line has a length of 102. Maximum allowed is 80  max-len
   59:1   error    This line has a length of 87. Maximum allowed is 80   max-len
   59:75  warning  'context' is defined but never used                   @typescript-eslint/no-unused-vars
   60:10  error    There should be no space after '{'                    object-curly-spacing
   60:33  error    There should be no space before '}'                   object-curly-spacing
   63:1   error    This line has a length of 106. Maximum allowed is 80  max-len
   69:1   error    This line has a length of 109. Maximum allowed is 80  max-len
   73:15  error    There should be no space after '{'                    object-curly-spacing
   73:76  error    There should be no space before '}'                   object-curly-spacing
   80:1   error    This line has a length of 86. Maximum allowed is 80   max-len
   81:1   error    This line has a length of 81. Maximum allowed is 80   max-len
   81:15  error    There should be no space after '{'                    object-curly-spacing
   81:79  error    There should be no space before '}'                   object-curly-spacing
   84:1   error    This line has a length of 91. Maximum allowed is 80   max-len
   87:1   error    This line has a length of 103. Maximum allowed is 80  max-len
   88:1   error    This line has a length of 95. Maximum allowed is 80   max-len
   88:15  error    There should be no space after '{'                    object-curly-spacing
   88:93  error    There should be no space before '}'                   object-curly-spacing
   90:1   error    This line has a length of 91. Maximum allowed is 80   max-len
   91:15  error    There should be no space after '{'                    object-curly-spacing
   91:76  error    There should be no space before '}'                   object-curly-spacing
   95:1   error    This line has a length of 102. Maximum allowed is 80  max-len
  100:1   error    This line has a length of 98. Maximum allowed is 80   max-len
  102:1   error    This line has a length of 93. Maximum allowed is 80   max-len
  104:1   error    This line has a length of 117. Maximum allowed is 80  max-len
  111:1   error    This line has a length of 89. Maximum allowed is 80   max-len
  112:1   error    Trailing spaces not allowed                           no-trailing-spaces
  120:13  error    There should be no space after '{'                    object-curly-spacing
  120:63  error    There should be no space before '}'                   object-curly-spacing
  123:1   error    This line has a length of 90. Maximum allowed is 80   max-len

✖ 40 problems (39 errors, 1 warning)
  14 errors and 0 warnings potentially fixable with the `--fix` option.

Error: functions predeploy error: Command terminated with non-zero exit code 1