Error: ENOENT: no such file or directory, open '/home/user/studio/.next/server/app-paths-manifest.json'     at readFileSync (node:fs:449:20)
    at loadManifest (file:///home/user/studio/node_modules/next/dist/server/load-manifest.js:36:52)

    at getMaybePagePath (file:///home/user/studio/node_modules/next/dist/server/require.js:51:59)

    at getPagePath (file:///home/user/studio/node_modules/next/dist/server/require.js:86:22)

    at requirePage (file:///home/user/studio/node_modules/next/dist/server/require.js:93:22)

    at loadComponentsImpl (file:///home/user/studio/node_modules/next/dist/server/load-components.js:129:57)

    at async DevServer.findPageComponentsImpl (file:///home/user/studio/node_modules/next/dist/server/next-server.js:808:36)

    at async DevServer.findPageComponents (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:628:16)

    at async DevServer.renderPageComponent (file:///home/user/studio/node_modules/next/dist/server/base-server.js:2379:24)

    at async DevServer.renderToResponseImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:2430:32)

    at async DevServer.pipeImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:1003:25)

    at async NextNodeServer.handleCatchallRenderRequest (file:///home/user/studio/node_modules/next/dist/server/next-server.js:304:17)

    at async DevServer.handleRequestImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:895:17)

    at async (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:371:20)

    at async Span.traceAsyncFn (file:///home/user/studio/node_modules/next/dist/trace/trace.js:157:20)

    at async DevServer.handleRequest (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:368:24)

    at async invokeRender (file:///home/user/studio/node_modules/next/dist/server/lib/router-server.js:247:21)

    at async handleRequest (file:///home/user/studio/node_modules/next/dist/server/lib/router-server.js:438:24)

    at async requestHandlerImpl (file:///home/user/studio/node_modules/next/dist/server/lib/router-server.js:462:13)

    at async Server.requestListener (file:///home/user/studio/node_modules/next/dist/server/lib/start-server.js:158:13)