Updated firebase functions and:
npm run build

> functions@1.0.0 build
> tsc

src/index.ts:36:4 - error TS2339: Property 'region' does not exist on type 'typeof import("/home/user/studio/functions/node_modules/firebase-functions/lib/v2/in
dex")'.
36   .region("europe-west1")
      ~~~~~~

src/index.ts:100:4 - error TS2339: Property 'region' does not exist on type 'typeof import("/home/user/studio/functions/node_modules/firebase-functions/lib/v2/i
ndex")'.
100   .region("europe-west1")
       ~~~~~~

src/index.ts:194:4 - error TS2339: Property 'region' does not exist on type 'typeof import("/home/user/studio/functions/node_modules/firebase-functions/lib/v2/i
ndex")'.
194   .region("europe-west1")
       ~~~~~~

Found 3 errors in the same file, starting at: src/index.ts:36